services:
  - type: web
    name: laundry-backend
    plan: free
    branch: main

    rootDir: backend

    buildCommand: ./mvnw clean package
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar

    envVars:
      - key: JAVA_VERSION
        value: 17
